### ISSUE TITLE
I am trying to run differential-line algorithm but can't download this dependency

### ISSUE THREAD

**Issue by nikivdev** [inconvergent/iutils#1]
I tried running ./install but get this error : 

`error: can't combine user with prefix, exec_prefix/home, or install_(plat)base`

What should I do?

Thank you for any help.

**Comment by inconvergent** [comment]
I've never seen that before. what python version are you on? mac? linux? can you please post all of the output, not just the single line? 

There is only one actual line of important code in the script, you can try it directly:

`python3 ./setup.py install --user`
